export const MODULES = {
  HOME: 'HOME',
  ICON: 'ICON',
  COLORS: 'COLORS',
  MODAL: 'MODAL',
  TOAST: 'TOAST',
  BADGE: 'BADGE',
  SEARCH: 'SEARCH',
  INDEX_LIST: 'INDEX_LIST',
  BUTTON: 'BUTTON',
};
